# Generated by Django 3.1.7 on 2021-03-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210328_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_comments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
